export enum View {
  PORTAL_SELECTION = 'PORTAL_SELECTION',
  STAFF_LOGIN = 'STAFF_LOGIN',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_CODE = 'VERIFY_CODE',
  SUCCESS = 'SUCCESS',
}
