export enum View {
  PORTAL_SELECTION = 'PORTAL_SELECTION',
  STAFF_LOGIN = 'STAFF_LOGIN',
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_CODE = 'VERIFY_CODE',
  RESET_PASSWORD = 'RESET_PASSWORcD', // New: Token verification + new PIN entry
  SUCCESS = 'SUCCESS',
}
